version: "3.6"

networks:
  appnetwork:
    driver: bridge

services:
  fcrepo:
    container_name: fcrepo-camel
    build:
      context: ./docker/services/fcrepo-camel
      args:
        FEDORA_TAG: ${FEDORA_TAG}
    image: fcrepo-camel
    networks:
      appnetwork:
        aliases:
          - fcrepo.docker.local
    ports:
      - 8080:8080
      - 8181:8181
